name = "kodesh-books"
compatibility_date = "2026-06-20"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "kodesh-books-db-v2"
database_id = "587caf85-8ac5-4b12-b417-70e7b730e551"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "kodesh-books-product-images-v2"
