name = "kodesh-books"
compatibility_date = "2026-06-20"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "otzar"
database_id = "173636cf-39cf-40cb-b869-51ffd6aea5f9"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "kodesh-books-product-images"
